# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 23:51
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_id', models.TextField(blank=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('rendered', models.TextField()),
                ('to_emails', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('from_email', models.TextField()),
                ('subject', models.TextField()),
                ('content_type', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.TextField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Email')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('content_type', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.EmailGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chance', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('choice_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_experiment_choice', to='root.EmailTemplate')),
                ('choice_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_experiment_choice', to='root.EmailTemplate')),
                ('email_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.EmailGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('apikey', models.TextField()),
                ('service', models.TextField(choices=[('sendgrid', 'Sendgrid')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('apikey', models.UUIDField(default=uuid.uuid4)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='providerconfig',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.UserGroup'),
        ),
        migrations.AddField(
            model_name='emailgroup',
            name='default_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='root.EmailTemplate'),
        ),
        migrations.AddField(
            model_name='emailgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.UserGroup'),
        ),
        migrations.AddField(
            model_name='email',
            name='email_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.EmailGroup'),
        ),
        migrations.AddField(
            model_name='email',
            name='experiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='root.Experiment'),
        ),
        migrations.AddField(
            model_name='email',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.ProviderConfig'),
        ),
        migrations.AddField(
            model_name='email',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='root.EmailTemplate'),
        ),
    ]
