# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='name',
            field=models.TextField(default='test-name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='name',
            field=models.TextField(default='test-name'),
            preserve_default=False,
        ),
    ]
