# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 23:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_auto_20171116_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='preview_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'content': 'hello world'}),
        ),
    ]
