# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_emailtemplate_preview_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='subject',
            field=models.TextField(default='default subject'),
            preserve_default=False,
        ),
    ]
